### PR TITLE
[YTS-57]: Yandex Tracker action: task not found

### PR DESCRIPTION
**Pull request by soltanoff**
https://tracker.yandex.ru/YTS-57

- code reformat (a little bit)
- added logging instead of print
- fixed data analysing and warning informing
- added linters and friends
- fixed Docker file
- moved to Python 3.11 
- updated all packages
- ~moved to poetry~ (poetry is large for this scripts)

### CODE REVIEW

**Comment by soltanoff** [comment]
Need squash

**Review by golyshevskii — APPROVED** [review]

**Comment by rapIsKal** [comment]
as for me, I would split MR into part that fixing the bug and part that does all the other stuff, but it's  just a point of view you can just easily skip it)

**Comment by soltanoff** [comment]
> 
as for me, I would split MR into part that fixing the bug and part that does all the other stuff, but it's just a point of view you can just easily skip it)

@rapIsKal, there is no bug fix - only code polishing and logging

**Comment by soltanoff** [comment]
For example: 
```
Run ./
Building docker image
...
+ cd /github/workspace
+ exec python /main.py
[SKIPPING] YTS-57 has error: {"errors":{},"errorMessages":["bad oauth status: INVALID: expired_token"],"statusCode":401}
```

**Pull request merged**
